### ISSUE TITLE
FYI, `debian | add Rabbitmq erlang repo key` task is unnecessary

### ISSUE THREAD

**Issue by jf** [mrlesmithjr/ansible-rabbitmq#27]
https://github.com/mrlesmithjr/ansible-rabbitmq/blob/master/tasks/debian.yml:

```
- name: debian | adding RabbitMQ public GPG key to the apt repo
  apt_key:
    url: "{{ rabbitmq_debian_repo_key }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | adding RabbitMQ repo
  ...

- name: debian | add Rabbitmq erlang repo key
  apt_key:
    url: https://bintray.com/user/downloadSubjectPublicKey?username=rabbitmq-erlang
    state: present
  become: true
  register: result
  until: result is successful
when: rabbitmq_debian_erlang_from_rabbit
```

`rabbitmq_debian_repo_key`, which is the same url as the url for the `debian | add Rabbitmq erlang repo key` task (see https://github.com/mrlesmithjr/ansible-rabbitmq/blob/master/defaults/main.yml#L26) is already added to apt_key in the first task above; there is no point in conditionally checking whether the same key should be added again.
